# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: my personal pc
- task: Maven@4
  inputs:
    azureSubscription: 'Azure for Students(8d426e93-4493-4f28-857a-e753f087f115)'
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  vmImage: ubuntu-latest

    - task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    mergeTestResults: true
    testRunTitle: 'Maven Unit Test Results'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'MyArtifact'
    publishLocation: 'FilePath'
    TargetPath: 'C:\MyLocalArtifacts\$(Build.BuildNumber)'
